- name: printing variables
  host: web
  tasks: #listing variable in different ways
  - name: normal declaration of variables
    COURSE: "JAVA"
    DURATION: 120hr
    ansible.builtin.apt:
    msg: "the COURSE:{{COURSE}},DURATION:{{DURATION}}"
